### ISSUE TITLE
生成時にエラーが発生

### ISSUE THREAD

**Issue by totoko00** [Katsuyuki-Karasawa/sdwebui-multi_restart#3]
以下のエラーが発生したので報告します。

>    Traceback (most recent call last):
      File "D:\SD\sd.webui\webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\SD\sd.webui\webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\SD\sd.webui\webui\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "D:\SD\sd.webui\webui\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "D:\SD\sd.webui\webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "D:\SD\sd.webui\webui\modules\processing.py", line 867, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "D:\SD\sd.webui\webui\modules\processing.py", line 1140, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "D:\SD\sd.webui\webui\modules\sd_samplers_kdiffusion.py", line 235, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "D:\SD\sd.webui\webui\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "D:\SD\sd.webui\webui\modules\sd_samplers_kdiffusion.py", line 235, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "D:\SD\sd.webui\webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\SD\sd.webui\webui\extensions\sdwebui-multi_restart\scripts\sd_samplers_multi_restart.py", line 50, in multi_restart_sampler
        restart_steps = int(config_data.get("restart_steps"))
    TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

t2iの設定は
サンプリングステップ数：60
サイズ：幅768　高さ1024

通常のサンプラー「Restart」は問題無く動作しました。

**Comment by L4Ph** [comment]
Extension読み込んだ後にApply and restartしてください

**Comment by L4Ph** [comment]
restart_stepsの値がsettingsにいますが、そいつが反映できていない(= 値が入っていない)ので

**Comment by totoko00** [comment]
解決しました。ありがとうございます。
仰る通りで、
「設定」タブの「設定を適用」ボタン押下したときに、restart_steps等の値が反映された旨が出ていたので、それができていなかったみたいです。

**Comment by L4Ph** [comment]
#2 一応直しました。
